// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaGestionLlaves.Data;

#nullable disable

namespace SistemaGestionLlaves.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225002656_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionLlaves.Models.AlertaNotificacion", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("FechaGenerada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generada")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("IdLlave")
                        .HasColumnType("integer")
                        .HasColumnName("id_llave");

                    b.Property<int?>("IdPrestamo")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestamo");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdLlave");

                    b.HasIndex("IdPrestamo");

                    b.HasIndex("Leida")
                        .HasDatabaseName("IX_Alerta_Leida");

                    b.ToTable("AlertaNotificacion", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Ambiente", b =>
                {
                    b.Property<int>("IdAmbiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ambiente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAmbiente"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<int>("IdTipo")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdAmbiente");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Ambiente_Codigo");

                    b.HasIndex("IdTipo");

                    b.ToTable("Ambiente", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text")
                        .HasColumnName("datos_nuevos");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("IdRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("id_registro");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operacion");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabla_afectada");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_Auditoria_Fecha");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TablaAfectada")
                        .HasDatabaseName("IX_Auditoria_Tabla");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.IntentoAcceso", b =>
                {
                    b.Property<int>("IdIntento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_intento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIntento"));

                    b.Property<bool>("Exitoso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exitoso");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("IdIntento");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_IntentoAcceso_Fecha");

                    b.ToTable("IntentoAcceso", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Llave", b =>
                {
                    b.Property<int>("IdLlave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_llave");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLlave"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsMaestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_maestra");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("D")
                        .HasColumnName("estado");

                    b.Property<int>("IdAmbiente")
                        .HasColumnType("integer")
                        .HasColumnName("id_ambiente");

                    b.Property<int>("NumCopias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("num_copias");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdLlave");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Llave_Codigo");

                    b.HasIndex("IdAmbiente");

                    b.ToTable("Llave", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("IdPermiso");

                    b.HasIndex("NombrePermiso")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permiso_Nombre");

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ci");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("genero");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.HasKey("IdPersona");

                    b.HasIndex("Ci")
                        .IsUnique()
                        .HasDatabaseName("UQ_Persona_Ci");

                    b.HasIndex("Correo")
                        .HasDatabaseName("IX_Persona_Correo");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.PersonaAutorizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLlave")
                        .HasColumnType("integer")
                        .HasColumnName("id_llave");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.HasKey("Id");

                    b.HasIndex("IdLlave");

                    b.HasIndex("IdPersona", "IdLlave")
                        .IsUnique()
                        .HasDatabaseName("UQ_PersonaAutorizada_PersonaLlave");

                    b.ToTable("Persona_Autorizada", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prestamo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrestamo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaHoraDevolucionEsperada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora_devolucion_esperada");

                    b.Property<DateTime?>("FechaHoraDevolucionReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora_devolucion_real");

                    b.Property<DateTime>("FechaHoraPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora_prestamo")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdLlave")
                        .HasColumnType("integer")
                        .HasColumnName("id_llave");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Prestamo_Estado");

                    b.HasIndex("FechaHoraPrestamo")
                        .HasDatabaseName("IX_Prestamo_Fecha");

                    b.HasIndex("IdLlave");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Prestamo", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("P")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdLlave")
                        .HasColumnType("integer")
                        .HasColumnName("id_llave");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdReserva");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Reserva_Estado");

                    b.HasIndex("IdLlave");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Rol_Nombre");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.TipoAmbiente", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("IdTipo");

                    b.HasIndex("NombreTipo")
                        .IsUnique()
                        .HasDatabaseName("UQ_TipoAmbiente_Nombre");

                    b.ToTable("TipoAmbiente", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_NombreUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.AlertaNotificacion", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Llave", "Llave")
                        .WithMany("Alertas")
                        .HasForeignKey("IdLlave")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaGestionLlaves.Models.Prestamo", "Prestamo")
                        .WithMany("Alertas")
                        .HasForeignKey("IdPrestamo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Llave");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Ambiente", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.TipoAmbiente", "TipoAmbiente")
                        .WithMany("Ambientes")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAmbiente");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Auditoria", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Llave", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Ambiente", "Ambiente")
                        .WithMany("Llaves")
                        .HasForeignKey("IdAmbiente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.PersonaAutorizada", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Llave", "Llave")
                        .WithMany("PersonasAutorizadas")
                        .HasForeignKey("IdLlave")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Persona", "Persona")
                        .WithMany("PersonasAutorizadas")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Llave");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Prestamo", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Llave", "Llave")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdLlave")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Persona", "Persona")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Llave");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Reserva", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Llave", "Llave")
                        .WithMany("Reservas")
                        .HasForeignKey("IdLlave")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Persona", "Persona")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Llave");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.RolPermiso", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Usuario", b =>
                {
                    b.HasOne("SistemaGestionLlaves.Models.Persona", "Persona")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionLlaves.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Ambiente", b =>
                {
                    b.Navigation("Llaves");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Llave", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("PersonasAutorizadas");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Persona", b =>
                {
                    b.Navigation("PersonasAutorizadas");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Prestamo", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.TipoAmbiente", b =>
                {
                    b.Navigation("Ambientes");
                });

            modelBuilder.Entity("SistemaGestionLlaves.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
